### ISSUE TITLE
Update to use latest coding standards

### ISSUE THREAD

**Issue by idmontie** [asu-ke-web-services/wordpress-coding-standards#2]
The following github repo has up to date coding standards for Wordpress:

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

Specifically, we want to upgrade [the OperatorSpacingSniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php).  Akash has manually upgraded this file in order for the coding standards to not tell him to intend stupid lines.

**Comment by idmontie** [comment]
Tagging @rraub.

**Comment by rraub** [comment]
This will also require us to use the php code sniffer v2 in our projects. 
```js
{
    "require-dev": {
        "squizlabs/php_codesniffer": "2.*"
    }
}
```

**Comment by rraub** [comment]
@nisarakash phpcs v2.* provides some utilities for fixing errors automatically: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically

**Comment by idmontie** [comment]
Is it possible to have Grunt two tasks; one that will auto correct errors that we can run on our local machines, and one that will NOT auto correct errors that will run on Travis?

**Comment by rraub** [comment]
It's a different binary to fix files (phpcbf) it takes the same arguments. So we could create two tasks, one with a different 'bin' definition thats pointing to phpcbf if we really wanted to.
